apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-temperature-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-temp
  template:
    metadata:
      labels:
        app: weather-temp
    spec:
      containers:
        - name: fastapi-weather-app
          image: dinakhadka/weather-temperature-analysis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000