apiVersion: v1
kind: Service
metadata:
  name: weather-temperature-service
spec:
  selector:
    app: weather-temp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP